name: movewise
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_gauges: ^23.1.40
#  shared_preferences: ^2.2.0
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
  get: ^4.7.2
  http: ^1.5.0
  markdown_widget: ^2.3.2+8
  flutter_markdown_plus: ^1.0.2
  animate_do: ^4.2.0
  percent_indicator: ^4.2.5
  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2

  google_sign_in: ^6.2.1
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
#  firebase_core: ^3.15.2
#  google_sign_in: ^5.4.4
  flutter_launcher_icons: ^0.14.4
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  lottie: ^3.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/Mlogo.png"
  image_path_ios: "assets/images/Mlogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:

  assets:
    - assets/images/background.jpg
    - assets/images/
    - assets/images/background.png
    - assets/images/google.png
    - assets/images/logo2.png
    - assets/json/
    - assets/video/v1.png
    - assets/video/v2.png
    - assets/video/v3.png
    - assets/video/v4.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
